{% set data= load_setup_py_data() %}
package:
  name: "ts-ess-common"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  script_env:
    - PATH
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - PYTHON_BUILD_LOCATION
    - LSST_DDS_PARTITION_PREFIX

test:
  requires:
    - ts-conda-build =0.3
    - ts-tcpip
    - ts-utils
  source_files:
    - python
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-tcpip
    - ts-utils
