{% set data= load_setup_py_data() %}

package:
  name: "ts-ess-common"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - PATH
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - PYTHON_BUILD_LOCATION
    - LSST_DDS_PARTITION_PREFIX

test:
  requires:
    - ts-conda-build =0.3
    - ts-tcpip
    - ts-utils
  source_files:
    - python
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - py.test

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-tcpip
    - ts-utils
